trigger:
- master
- rel/*

pr:
- master
- rel/*

pool:
  vmImage: 'windows-2019'

variables: 
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  BuildConfiguration: Release
  RepositoryLocalPath : $(Build.Repository.LocalPath)

steps:

- task: NuGetToolInstaller@0
  displayName: Use NuGet 5.0.0
  inputs:
    versionSpec: 5.0.0

- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '3.0.100'
  displayName: Use .NET Core sdk

- task: DotNetCoreCLI@2
  inputs:
    command: custom
    custom: tool
    arguments: install --tool-path . nbgv
  displayName: Install NBGV tool

- script: nbgv cloud
  displayName: Set Version

- task: BatchScript@1
  inputs:
    filename: "C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Enterprise\\Common7\\Tools\\VsDevCmd.bat"
    arguments: -no_logo
    modifyEnvironment: true
  displayName: Setup Environment Variables

- task: NuGetCommand@2
  displayName: NuGet restore Native projects
  inputs:
    command: restore
    configuration: Release
    restoreSolution: Microsoft.Toolkit.Win32.UI.XamlApplication\packages.config
    restoreDirectory: ../packages/
    verbosityRestore: Detailed # Options: quiet, normal, detaile

- task: MSBuild@1
  displayName: Build x64 Restore
  inputs:
    solution: Microsoft.Toolkit.Win32.sln 
    platform: x64
    configuration: Release
    msbuildArguments: /target:Restore
    restoreNugetPackages: false # Optional

- task: MSBuild@1
  displayName: Build x64
  inputs:
    solution: Microsoft.Toolkit.Win32.sln 
    platform: x64
    configuration: Release
    msbuildArguments: /target:Build
    restoreNugetPackages: false # Optional

- powershell: "& 'C:\\Program Files (x86)\\Windows Kits\\10\\Debuggers\\x64\\pdbcopy.exe' $env:RepositoryLocalPath\\x64\\Release\\Microsoft.Toolkit.Win32.UI.XamlApplication\\Microsoft.Toolkit.Win32.UI.XamlHost.pdb $env:RepositoryLocalPath\\x64\\Release\\Microsoft.Toolkit.Win32.UI.XamlApplication\\Microsoft.Toolkit.Win32.UI.XamlHost_stripped.pdb -p"
  displayName: Strip x64

- task: MSBuild@1
  displayName: Build x86 Restore
  inputs:
    solution: Microsoft.Toolkit.Win32.sln 
    platform: x86
    configuration: Release
    msbuildArguments: /target:Restore
    restoreNugetPackages: false # Optional

- task: MSBuild@1
  displayName: Build x86
  inputs:
    solution: Microsoft.Toolkit.Win32.sln 
    platform: x86
    configuration: Release
    msbuildArguments: /target:Build
    restoreNugetPackages: false # Optional

- powershell: "& 'C:\\Program Files (x86)\\Windows Kits\\10\\Debuggers\\x64\\pdbcopy.exe' $env:RepositoryLocalPath\\Win32\\Release\\Microsoft.Toolkit.Win32.UI.XamlApplication\\Microsoft.Toolkit.Win32.UI.XamlHost.pdb $env:RepositoryLocalPath\\Win32\\Release\\Microsoft.Toolkit.Win32.UI.XamlApplication\\Microsoft.Toolkit.Win32.UI.XamlHost_stripped.pdb -p"
  displayName: Strip x86

- task: MSBuild@1
  displayName: Build ARM Restore
  inputs:
    solution: Microsoft.Toolkit.Win32.sln 
    platform: ARM
    configuration: Release
    msbuildArguments: /target:Restore
    restoreNugetPackages: false # Optional

- task: MSBuild@1
  displayName: Build ARM
  inputs:
    solution: Microsoft.Toolkit.Win32.sln 
    platform: ARM
    configuration: Release
    msbuildArguments: /target:Build
    restoreNugetPackages: false # Optional

- powershell: "& 'C:\\Program Files (x86)\\Windows Kits\\10\\Debuggers\\x64\\pdbcopy.exe' $env:RepositoryLocalPath\\ARM\\Release\\Microsoft.Toolkit.Win32.UI.XamlApplication\\Microsoft.Toolkit.Win32.UI.XamlHost.pdb $env:RepositoryLocalPath\\ARM\\Release\\Microsoft.Toolkit.Win32.UI.XamlApplication\\Microsoft.Toolkit.Win32.UI.XamlHost_stripped.pdb -p"
  displayName: Strip ARM

- task: MSBuild@1
  displayName: Build ARM64 Restore
  inputs:
    solution: Microsoft.Toolkit.Win32.sln 
    platform: ARM64
    configuration: Release
    msbuildArguments: /target:Restore
    restoreNugetPackages: false # Optional

- task: MSBuild@1
  displayName: Build ARM64
  inputs:
    solution: Microsoft.Toolkit.Win32.sln 
    platform: ARM64
    configuration: Release
    msbuildArguments: /target:Build
    restoreNugetPackages: false # Optional

- powershell: "& 'C:\\Program Files (x86)\\Windows Kits\\10\\Debuggers\\x64\\pdbcopy.exe' $env:RepositoryLocalPath\\ARM64\\Release\\Microsoft.Toolkit.Win32.UI.XamlApplication\\Microsoft.Toolkit.Win32.UI.XamlHost.pdb $env:RepositoryLocalPath\\ARM64\\Release\\Microsoft.Toolkit.Win32.UI.XamlApplication\\Microsoft.Toolkit.Win32.UI.XamlHost_stripped.pdb -p"
  displayName: Strip ARM64

- task: MSBuild@1
  displayName: Build Pack
  inputs:
    solution: Microsoft.Toolkit.Win32.sln 
    platform: x86
    configuration: Release
    msbuildArguments: /target:Pack
    restoreNugetPackages: false # Optional

- task: PowerShell@2
  displayName: Authenticode Sign Packages
  inputs:
    filePath: build/Sign-Package.ps1
  env:
    SignClientUser: $(SignClientUser)
    SignClientSecret: $(SignClientSecret)
    ArtifactDirectory: bin\nupkg
  condition: and(succeeded(), not(eq(variables['build.reason'], 'PullRequest')), not(eq(variables['SignClientSecret'], '')), not(eq(variables['SignClientUser'], '')))

- task: PublishBuildArtifacts@1
  displayName: Publish Package Artifacts
  inputs:
    pathToPublish: .\bin\nupkg
    artifactType: container
    artifactName: Packages

# Publish stripped pdbs to artifacts
- task: CopyFiles@2
  inputs:
    Contents: |
      x64\$(Configuration)\Microsoft.Toolkit.Win32.UI.XamlApplication\Microsoft.Toolkit.Win32.UI.XamlHost_stripped.pdb
      Win32\$(Configuration)\Microsoft.Toolkit.Win32.UI.XamlApplication\Microsoft.Toolkit.Win32.UI.XamlHost_stripped.pdb
      arm\$(Configuration)\Microsoft.Toolkit.Win32.UI.XamlApplication\Microsoft.Toolkit.Win32.UI.XamlHost_stripped.pdb
      arm64\$(Configuration)\Microsoft.Toolkit.Win32.UI.XamlApplication\Microsoft.Toolkit.Win32.UI.XamlHost_stripped.pdb
    TargetFolder: '$(Build.ArtifactStagingDirectory)\symbols\'

- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: '$(Build.ArtifactStagingDirectory)\symbols' 
    artifactName: 'symbols' 
